## 0. 들어가면서
* 예전에 자바의 조건문과 예외처리의 차이점과 목적에 대해 공부했다.
* 오늘은 자바의 예외 처리에 대해 집중적으로 공부해보고자 한다.
* 자바 예외 처리를 본격적으로 공부하기 앞서, 몇 가지 개념을 간단하게 짚고 넘어가고자 한다.
```
1. Error: 프로그램 코드에 의해 핸들링될 수 없는 것(Compile error, Runtime error, Logic error)
2. Exceptions: 프로그램 코드를 통해 핸들링할 수 있는 것들
3. Exception handling: 프로그램에서 일어날 수 있는 예외 상황을 고려하여 코드로 이 부분을 핸들링하는 것
```

## 1. 자바의 예외 처리 방법
* 자바의 예외 처리는 기본적으로 예외가 던져지고(Throw) -> 이를 처리하는(Handling) 방식으로 이루어진다.

### 1) try-catch
* 자바를 해봤으면 누구나 보았을 try-catch문의 예시를 보자.
```java
try{
    // 예외를 일으킬만한 내용들을 이 곳에 쓴다.
} catch (Exception1 e1){
    // Exception1라는 예외가 발생하면 이를 핸들링한다.
} catch (Exception e2){
    // Exception2라는 예외가 발생하면 이를 핸들링한다.
}
...
- 위는 정말 기본적인 try-catch문의 구조이다. try문 안에서 예외를 일으킬만한 내용을 미리 적고, 실제로 예외가 발생하면 catch문에서 예외에 따라 적절한 방식으로 대응한다.
- 이 부분에서 짐작할 수 있듯이, 만약 try문 안에서 예외가 발생했는데 이 예외를 catch문에서 잡아내지 못하면 이것은 그대로 프로그램이 비정상적으로 종료되거나 하는 결과를 낳게 된다.
- 한편, try문 안에서 아무 예외가 발생되지 않으면 프로그램은 그냥 try문을 수행하고 try-catch 바깥 블록의 코드를 이어서 수행한다.

```

### 2) throw
* 아래 예시는 **throw**를 통해서 일부러 예외를 발생시키는 것이다.
* 맨 처음에 우리는 Error와 Exception의 차이를 잠깐 짚어보고 왔다. 여기서 Exception을 일부러 발생시키는 이유를 알 수 있는데, **Error와는 다르게 Exception은 개발자의 의도한 방향이 아닌 방향으로 사용자가 프로그램을 동작하면 이에 대해 일부러 Exception을 발생시킴으로써 잘못된 사용을 방지하는 것이다.**
* 아래 예시를 보자.
```java
import java.util.Scanner;

public class DanceLesson
{
    public static void main(String[] args)
    {
        Scanner sc = new Scanner(System.in);
        System.out.println(Enter number of participants: ");
        int participants = sc.nextdInt();
        
        try{
            if (parcipants <= 0)
                throw new Exception("Lesson is Canceled. No Participants.");
            System.out.println("There are " + participants + " people in class.");
        } catch (Exception e){
            String message = e.getMessage();
            System.out.println(message);
            System.exit(0);
        }
        
        System.out.println("Begin the lesson.");
    }
}

// 이 예시에서는 만약 수업에 참여하는 사람이 0명 이하일 때는 예외를 발생시킴으로써 프로그램이 종료되도록 하는 것이다.
// 실제 생활에서 위와 같은 예외처리는 별로 없을 것 같지만 throw를 어떻게 사용하는지만 확인하면 될 것 같다.
```

### 3) throws
* throws는 예외가 발생한 곳에서 try-catch 블록으로 직접 처리하지 않고, 메서드를 호출한 곳으로 예외를 떠넘길 때 사용한다.
* 예외 처리를 위임방은 메서드는 다시 예외 처리에 대한 책임이 있고, 자신이 직접 이 예외를 처리하거나 또 다시 다른 곳으로 떠넘길 수 있다.
* 하지만 만약 어떤 곳에서도 이 예외를 제대로 처리하지 않으면 프로그램은 비정상적으로 터지게 된다. 
<img src = "https://user-images.githubusercontent.com/61929745/118476923-15225800-b749-11eb-9c88-00f44efa238f.png" width = 800 heigth = 600>


* 위 그림을 보면 Call Stack에 main -> method1 -> method2 순서로 쌓이게 되는데, method2에서 예외가 발생하면 method2는 이 예외를 자신을 호출한 method1에게 떠넘긴다.
* 이 때, method1은 이 예외를 직접 처리하지 않고 다시 자신을 호출한 main에게 떠넘기고, main이 이를 처리해야 되는데 또 예외를 처리하지 않아서 결국 runtime exception문제가 생기는 것이다.

### 4) finally
* finally문은 try-catch-finally 구조로 사용되는데, 예외가 발생하거나 발생하지 않거나 무조건 최종적으로 거쳐가는 곳이다.
* finally문에 대한 예시는 너무 길어지는 것 같아서 따로 정리하지는 않겠다.

---

## 2. 자바 예외 계층 구조(Exception Class)
* 자바 Exception Class는 크게 두 가지가 있다.
1. RuntimeException Class(Arithmetic, ClassCast, NullPointer, IndexOutOfBounds ...) = Unchecked Exception
```
- 이 예외는 우리가 가장 많이 접하는 예외로, 쉽게 생각해서 코딩을 잘못해서 발생하는 예외다.
- 이러한 예외에 대해서는 예외를 처리해놓지 않아도 컴파일 에러가 발생하지는 않는다. 다만 런타임에 프로그램이 터지게 된다.
- 아마 많이 경험했으리라 생각한다..
```

2. Other Exception Class(IOException, ClassNotFoundException ...) = Checked Exception
```
- 이 예외는 우리가 일부러 발생시키는 예외처럼 사용자가 잘못된 입력을 하는 상황 등에 대한 예외를 의미한다.
- 이전에 봤던 것처럼 이런 예외를 제대로 처리하지 않으면 Compile error가 발생한다.
- 쉽게 생각해서 우리가 일부러 이런 저런 예외를 고려하면서 큰 그림을 그려놨는데, 정작 예외 처리가 되어있지 않으면 컴파일러가 뭔가 이상하다고 생각하는 것이다.
```
#### 위 두 가지 예외 계층에 대해 한 가지 더 알아둘 내용이 있는데 바로 Transaction의 Rollback 여부이다.
- RuntimeException 같은 경우에는 예외 발생 시 트랜잭션을 rollback하고, 그 외 Exception들은 트랜잭션을 rollback하지 않는다.
- 따라서, 두 예외에서 rollback의 범위가 다르기 때문에 이를 인지하지 못하면 프로그램의 수행결과 등이 예상치 못하는 방향으로 나타나거나 비즈니스 로직이 깨질 수 있다.

- 가령 우리가 어떤 사이트에서 회원가입을 하면 쿠폰이 발급되도록 하는 기능을 만든다고 해보자. 
- 그런데 이 과정에서 어떤 문제가 발생해서 회원가입과 쿠폰 발급이 동시에 완료되지 못하면 어떻게 될까?
```java
// 다음과 같은 Service Component가 존재한다고 생각해보자.
@Service
public class UserService{
    @Autowired
    private CouponRepositoty couponRepository;
    
    @Transactional
    public void signUpUser1(UserDto UserDto) throws Exception{
        save(userDto);
        try{
            throw new Exception();
            couponRepository.issueCoupon(userDto.getId());
        } catch(Exception ex) 
            { // skip 
        } 
    }
    
    @Transactional
    public void signUpUser2(UserDto userDto) throws RuntimeException{
        couponRepository.issueCoupon(userDto.getId());
        save(userDto);
        throw new RuntimeException("RuntimeException for rollback");
    }
}
```
#### 1) 만약 회원 가입은 허용하지만, 쿠폰 발급은 보류해도 된다고 하면? 
* 아래와 같이 Check Exception을 발생시켰지만, 회원 정보는 생성되고 쿠폰 발급은 문제없이 진행된다.
```java
@Transactional
public void signUpUser1(UserDto UserDto) throws Exception{
    save(userDto);
    try{
        throw new Exception();
        couponRepository.issueCoupon(userDto.getId());
    } catch(Exception ex) 
        { // skip 
    } 
    // Rollback 없이 Transaction 완료
}
// 스프링에서는 @Transactional을 사용한 Checked Exception은 rollback되지 않는다.
```
#### 2) 회원 가입과 쿠폰 발급이 동시에 완료되지 못한 경우에는 모두 Rollback 되어야 한다면?
* RuntimeException이 발생하고 동시에 모두 Rollback된다.
```java
public void signUpUser2(UserDto userDto) throws RuntimeException{
    couponRepository.issueCoupon(userDto.getId());
    save(userDto);
    throw new RuntimeException("RuntimeException for rollback");
}
```

* 아래 그림은 방금 살펴본 Exception Class의 구조이다. 참고하면 좋을 것 같다.   
![image](https://user-images.githubusercontent.com/61929745/118478192-8ca4b700-b74a-11eb-87d0-25b8c0f12e1a.png)

---
## 3. 커스텀 예외 만들기
* 예전에 클린코드라는 책을 조금씩 정리했을 때, 예외처리에 대한 클린코드 내용도 있었다.
* 사용자 정의 예외(커스텀 예외)는 분명 필요하지만, 너무 많은 커스텀 예외를 일일이 만드는 것은 기존에 이미 있는 RuntimeException을 충분히 활용하지 못할 가능성을 만들게 된다.
* 인수로 부적절한 값이 들어올 때 던지는 IllegalArgumentException, 일을 수행하기에 적합하지 않은 상태의 객체인 경우 던지는 IllegalStateException 등 이미 표준적으로 사용되고 있는 예외들을 적절히 잘 사용하는 것이 우선 중요하다고 생각할 수 있다.
* 하지만 그럼에도 불구하고 커스텀 예외는 다음과 같은 장점을 갖는다.
```
1. 이름으로도 정보 전달이 가능하다.
- NoSuchElementException, PostNotFoundException같은 예외는 이름만 봐도 무슨 예외가 발생했는지 쉽게 파악할 수 있다.
2. 상세한 예외 정보를 제공할 수 있다.
- 예를들어 IndexOutOfBoundsException을 생각해보자.
- 이 예외가 발생하게 되면 우리는 전체 범위가 얼만큼인지, 어디에서 예외가 발생했는지 쉽게 파악하기 어렵다.
- 따라서 아래처럼 IndexOutOfBoundsException Class를 오버로딩하여 정보를 전달할 수 있다.
```
```java
public class IllegalIndexException extends IndexOutOfBoundsException {
	private static final String message = "범위를 벗어났습니다.";

	public IllegalIndexException(List<?> target, int index) {
		super(message + " size: "  + target.size() + " index: " + index);
	}
}
````
```
- 이 외에도 커스텀 예외를 만들어두면 예외에 필요한 메시지, 전달할 정보의 데이터, 데이터 가공 메소드등을 한 곳에 관리함으로써 객체의 책임이 분리된 코드를 만들수도 있다.
```

#### 그렇다면 커스텀 예외는 어떤 식으로 만들까?
* 위에서 살펴본 것처럼 기존에 존재하는 특정한 Exception Class를 오버로딩하여 구체적인 정보를 전달하는 식으로 커스텀 예외를 생성할 수 있다.
* 또한 모든 예외들의 Parent인 Exception Class를 extends하여 그 곳에 멤버 변수 형태로 내가 원하는 예외를 정의할 수도 있다.
* 아래 간단한 예시를 보자.
```java
public class DivisionByZeroException extends Exception
{
    public DivisionByZeroException(){
        super("Division by Zero!");
    }
    
    public DivisionByZeroException(String message){
        super(message);
    }
}
-------------------------------------------------------
import java.util.Scanner;

public class Practice
{
    public static void main(String[] args){
        try{
            Scanner sc = new Scanner(System.in);
            
            System.out.println("Enter numerator:");
            int numerator = sc.nexdtInt();
            System.out.println("Enter denominator:");
            int denominator = sc.nexdtInt();
            
            if (denominator == 0)
                throw  new DivisionByZeroException();
            
            // 예외가 발생하지 않았을 때 statements...
        } catch (DivisionByZeroException e){
            System.out.println(e.getMessage());
        }
    }
    ...
}
```
---

## 4. 나가면서
* 지금까지 자바에서 예외를 처리하는 방법에 대해 공부했다.
* 예외 처리는 기본적으로 try-catch-finally문으로 구성되며 구체적으로 들여다보면 직접 예외를 발생시키는 throw, 예외의 책임을 전가하는 throws, 그리고 사용자가 직접 정의하는 커스텀 예외 등이 있었다. 그리고 예외의 클래스에 따라서 RuntimeException class(Unchecked), Other class(Checked)로 나누어볼 수 있었고 Checked Exception같은 경우 예외를 적절히 처리해주지 않으면 컴파일 에러가 발생하였다. 또한 두 예외의 rollback 범위도 차이가 있었는데, 이는 우리가 짜는 비즈니스 로직에 따라 분명 고려해야 하는 점이기도 했다.
* 예외 처리는 개념이 엄청 복잡하지는 않지만 하나하나 생각하다보면 골치가 아파지는 것 같다. 스프링을 공부하면서도 예외처리와 Transaction 처리들을 유심히 봐야겠다.


